server:
  port: 8081
spring:
  application:
    name: urban-lifestyle-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_redis_project?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.10.129
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.roger.urbanlifestyle.entity
logging:
  level:
    com:
      roger:
        urbanlifestyle: debug
  pattern:
    dateformat: mm:ss.SSS